name: Scheduled Scraper

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Specify the Python version you need

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Scraper
        env:
          SEARCH_QUERY: 'klipsch'
          CATEGORY: 'audio-tv-en-foto'
        run: |
          python scraper.py "$SEARCH_QUERY" "$CATEGORY"
